### ISSUE TITLE
Add config to enable header X-Guzzle-Stereo

### ISSUE THREAD

**Issue by estahn** [ikwattro/guzzle-stereo#5]
Would be great to have the possibility to automatically record the header `X-Guzzle-Stereo`. Eventually use DateTime (`Y-m-d H:m:i`) as value or just `True`.

Would help to identify during debugging if the response comes from stereo.

**Comment by ikwattro** [comment]
Great idea, fixed by https://github.com/ikwattro/guzzle-stereo/commit/cec1ef2becd72c629f7c7da3735d70064c862c80

Config option : 

```
marker_header: true
```

**Comment by ikwattro** [comment]
Released in 1.2.0

**Comment by estahn** [comment]
:+1:
