### ISSUE TITLE
Check directory before writing to it, not during initialisation

### ISSUE THREAD

**Issue by estahn** [ikwattro/guzzle-stereo#6]
Hi @ikwattro,

Could you move the check (https://github.com/ikwattro/guzzle-stereo/blob/cec1ef2becd72c629f7c7da3735d70064c862c80/src/Store/Writer.php#L29) to the write directory. It causes problems in the `guzzle-stereo-bundle` i wrote for symfony. The check should not happen during initialisation, rather when it's actually being used.

**Comment by ikwattro** [comment]
Hi @estahn , Good point, makes sense. I'm travelling today but will dig it in when back.

**Comment by ikwattro** [comment]
@estahn Fixed in 1.2.1
