### ISSUE TITLE
Symfony/finder dependency causing problem with installation.

### ISSUE THREAD

**Issue by jonnywilliamson** [ikwattro/guzzle-stereo#9]
Looks like Laravel 5.3 requires `symfony/finder 3.1*`

This project at the moment only requires `^2.7`, so I can't install it.

Do you think there would be problems if you were to change the dependency to `^2.7 | ^3.1` or similar?

**Comment by ikwattro** [comment]
No problem at all for me. Feel free to make a PR

**Comment by jonnywilliamson** [comment]
Will do.
